### ISSUE TITLE
直接定义的问题

### ISSUE THREAD

**Issue by oOTnTOo** [aeagean/QtNetworkService#12]
直接使用示例的话，除了作用域会直接导致Httplient被销毁，待到请求返回时回调不能执行，一般放入成员变量使用，但是会导致.Block设置后不能更改（同步调用一旦设置不能再改回异步）建议Block加入参数

**Comment by aeagean** [comment]
好的，这个建议不错。

**Comment by aeagean** [comment]
添加了静态方法和传参实现了。
