### ISSUE TITLE
文件下载，返回的totalSize为0

### ISSUE THREAD

**Issue by XIAODINGPA** [aeagean/QtNetworkService#17]
// 断点续传下载文件
  m_response = m_client.get(m_urlEdit->text())
                         .download()
                         .enabledBreakpointDownload(true)
                         .onDownloadFileNameChanged(this, SLOT(onDownloadFileNameChanged(QString)))
                         .onDownloadFileProgress(this, SLOT(onDownloadFileProgress(qint64,qint64)))
                         .onDownloadFileSuccess(this, SLOT(onDownloadFileSuccess(QString)))
                         .onDownloadFileFailed(this, SLOT(onDownloadFileFailed(QString)))
                         .exec();

void Downloader::onDownloadFileProgress(qint64 recv, qint64 total)
{
    qDebug()<<"Downloader::onDownloadFileProgress "<<" recv:"<<recv<<" total:"<<total;
    m_currentRecvSize = recv;
    m_totalSize       = total;
    m_currentSizeValueLabel->setText(toBytes(recv));
    m_fileSizeValueLabel->setText(toBytes(total));
    m_progressBar->setValue(100 * qreal(recv)/total);
}
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/28077025/169441858-8c222b67-43dd-47d8-befe-df2ab1bf5b0a.png">
Demo
[downloader-master.zip](https://github.com/aeagean/QtNetworkService/files/8735584/downloader-master.zip)
：

**Comment by 564398053** [comment]
我也遇到这个问题了.

**Comment by 564398053** [comment]
调试了一下，使用connect的方式就没问题. 源码不太看的懂，个人在客户端暂时先这样处理就可以获取进度了。
`connect(m_response, &AeaQt::HttpResponse::downloadProgress, this, &Downloader::onDownloadFileProgress);`
